spring:
    datasource:
        url: "jdbc:h2:mem:db-bvss"
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa.database-platform: org.hibernate.dialect.H2Dialect

server:
    port: 5000
    servlet:
        context-path: /bvss-es6-api-estoque
